version: "3.7"
# created with cookiecutter for project 'Demo Hello World'


#


services:
# ###
# ---------------------------------------------------------------------------
  cache:
    image: '${DOCKER_IMAGE_CACHE}'
    build:
      context: ./cache
      dockerfile: ../compose/local/cache/python3.9-slim.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
      - envs/local/cache
    environment:
      - LOG_LEVEL=debug
      - D4SERVICE_OAUTH2_URI=http://keycloak:8080
      - D4SERVICE_OAUTH2_PORT=8080
      - D4SERVICE_OAUTH2_CLIENT_ID=d4-client
      - D4SERVICE_OAUTH2_CLIENT_SECRET=1f02bb76-eb58-40e2-928d-13f5c35794c1
      - D4SERVICE_OAUTH2_ISSUER=http://keycloak:8080/auth/realms/demo-hello-world-realm
      - D4SERVICE_OAUTH2_AUTH_ENDPOINT=http://127.0.0.1:8080/auth/realms/demo-hello-world-realm/protocol/openid-connect/auth
      - D4SERVICE_OAUTH2_TOKEN_ENDPOINT=http://keycloak:8080/auth/realms/demo-hello-world-realm/protocol/openid-connect/token
      - D4SERVICE_OAUTH2_JWKS_URI=http://keycloak:8080/auth/realms/demo-hello-world-realm/protocol/openid-connect/certs
      - D4SERVICE_OAUTH2_USERINFO_ENDPOINT=http://keycloak:8080/auth/realms/demo-hello-world-realm/protocol/openid-connect/userinfo
      - D4SERVICE_OPA_URI=http://opa:8181
      - D4SERVICE_OPA_PORT=8181
      - D4SERVICE_CACHE_URI=http://127.0.0.1:9020
      # Allow explicit env var override for tests
    ports:
      - "${D4SERVICE_CACHE_PORT}:${D4SERVICE_CACHE_PORT}"
# #######
